"""test

Revision ID: 10847ea8454d
Revises: 7d5278403366
Create Date: 2023-12-01 21:49:31.087429

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10847ea8454d"
down_revision: Union[str, None] = "7d5278403366"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "zweite_stimme_ohne_kandidaten",
        sa.Column("StimmkreisId", sa.Integer(), nullable=True),
    )
    op.drop_constraint(
        "zweite_stimme_ohne_kandidaten_WahlkreisId_fkey",
        "zweite_stimme_ohne_kandidaten",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "zweite_stimme_ohne_kandidaten",
        "stimmkreis",
        ["StimmkreisId"],
        ["StimmkreisId"],
    )
    op.drop_column("zweite_stimme_ohne_kandidaten", "WahlkreisId")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "zweite_stimme_ohne_kandidaten",
        sa.Column("WahlkreisId", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "zweite_stimme_ohne_kandidaten", type_="foreignkey")
    op.create_foreign_key(
        "zweite_stimme_ohne_kandidaten_WahlkreisId_fkey",
        "zweite_stimme_ohne_kandidaten",
        "wahlkreis",
        ["WahlkreisId"],
        ["WahlkreisId"],
    )
    op.drop_column("zweite_stimme_ohne_kandidaten", "StimmkreisId")
    # ### end Alembic commands ###
