"""add abgeordnete

Revision ID: 3d7d5cd18aa5
Revises: 99facd099c84
Create Date: 2023-12-10 09:51:34.751341

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d7d5cd18aa5"
down_revision: Union[str, None] = "99facd099c84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "abgeordnete",
        sa.Column("KandidatID", sa.Integer(), nullable=False),
        sa.Column("Erststimme", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["KandidatID"],
            ["kandidaten.KandidatID"],
        ),
        sa.PrimaryKeyConstraint("KandidatID"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("abgeordnete")
    # ### end Alembic commands ###
