"""test

Revision ID: 93fd3af62192
Revises: 
Create Date: 2023-12-01 18:32:08.314283

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93fd3af62192"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parteien",
        sa.Column("ParteiID", sa.Integer(), nullable=False),
        sa.Column("Name", sa.String(), nullable=True),
        sa.Column("kurzbezeichnung", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("ParteiID"),
    )
    op.create_table(
        "wahlkreis",
        sa.Column("WahlkreisId", sa.Integer(), nullable=False),
        sa.Column("Name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("WahlkreisId"),
    )
    op.create_table(
        "stimmkreis",
        sa.Column("StimmkreisId", sa.Integer(), nullable=False),
        sa.Column("Name", sa.String(), nullable=True),
        sa.Column("Stimmberechtigte", sa.Integer(), nullable=True),
        sa.Column("WahlkreisId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["WahlkreisId"],
            ["wahlkreis.WahlkreisId"],
        ),
        sa.PrimaryKeyConstraint("StimmkreisId"),
    )
    op.create_table(
        "zweite_stimme_ohne_kandidaten",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("WahlkreisId", sa.Integer(), nullable=True),
        sa.Column("ParteiID", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ParteiID"],
            ["parteien.ParteiID"],
        ),
        sa.ForeignKeyConstraint(
            ["WahlkreisId"],
            ["wahlkreis.WahlkreisId"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kandidaten",
        sa.Column("KandidatID", sa.Integer(), nullable=False),
        sa.Column("Vorname", sa.String(), nullable=True),
        sa.Column("Nachname", sa.String(), nullable=True),
        sa.Column("ParteiID", sa.Integer(), nullable=True),
        sa.Column("StimmkreisId", sa.Integer(), nullable=True),
        sa.Column("ListenNummer", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ParteiID"],
            ["parteien.ParteiID"],
        ),
        sa.ForeignKeyConstraint(
            ["StimmkreisId"],
            ["stimmkreis.StimmkreisId"],
        ),
        sa.PrimaryKeyConstraint("KandidatID"),
    )
    op.create_table(
        "waehler",
        sa.Column("WaehlerID", sa.Integer(), nullable=False),
        sa.Column("Vorname", sa.String(), nullable=True),
        sa.Column("Nachname", sa.String(), nullable=True),
        sa.Column("Geburtsdatum", sa.Date(), nullable=True),
        sa.Column("StimmkreisId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["StimmkreisId"],
            ["stimmkreis.StimmkreisId"],
        ),
        sa.PrimaryKeyConstraint("WaehlerID"),
    )
    op.create_table(
        "erste_stimmzettel",
        sa.Column("Erste_StimmzettelID", sa.Integer(), nullable=False),
        sa.Column("KandidatID", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["KandidatID"],
            ["kandidaten.KandidatID"],
        ),
        sa.PrimaryKeyConstraint("Erste_StimmzettelID"),
    )
    op.create_table(
        "zweite_stimmzettel",
        sa.Column("Zweite_StimmzettelID", sa.Integer(), nullable=False),
        sa.Column("KandidatID", sa.Integer(), nullable=True),
        sa.Column("StimmkreisId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["KandidatID"],
            ["kandidaten.KandidatID"],
        ),
        sa.ForeignKeyConstraint(
            ["StimmkreisId"],
            ["stimmkreis.StimmkreisId"],
        ),
        sa.PrimaryKeyConstraint("Zweite_StimmzettelID"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("zweite_stimmzettel")
    op.drop_table("erste_stimmzettel")
    op.drop_table("waehler")
    op.drop_table("kandidaten")
    op.drop_table("zweite_stimme_ohne_kandidaten")
    op.drop_table("stimmkreis")
    op.drop_table("wahlkreis")
    op.drop_table("parteien")
    # ### end Alembic commands ###
