"""test

Revision ID: 99facd099c84
Revises: 10847ea8454d
Create Date: 2023-12-03 18:06:27.502974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99facd099c84"
down_revision: Union[str, None] = "10847ea8454d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wahlkreis", sa.Column("Abgeordnetenmandate", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wahlkreis", "Abgeordnetenmandate")
    # ### end Alembic commands ###
